---
- name: Install necessary packages
  vars:
      yum_retries: 3
  yum: name="{{ item  }}" state=present
  with_items:
    - http://stackforce.cloudlinux.com/repos/consul-0.6.3-1.el7.centos.x86_64.rpm
  register: yum_result
  until: yum_result.msg == "All items completed"
  retries: "{{ yum_retries }}"

- name: Default consul config
  template: src=consul.json.j2 dest=/etc/consul/consul.json owner=root group=consul

- name: Enable consul
  service: name=consul state=restarted enabled=yes
