---
- name: Create log dirs
  file: path=/var/log/mysql_logs state=directory mode=0755
- name: Copy my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify: Restart mysql

- name: Remove default configs
  shell: rm -rf /etc/my.cnf.d/*

- name: Copy cluster.conf
  template:
    src: cluster.cnf.j2
    dest: /etc/my.cnf.d/cluster.cnf
  notify: Restart mysql
