---

- name: Restart Neutron services
  service: name="{{ item }}" state=restarted
  with_items:
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
