---
- name: EPEL repository
  yum: name="{{ item }}" state=present
  with_items:
    - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
  tags:
    - yum
  ignore_errors: true

- name: KVM packages
  yum: name="{{ item }}" state=present
  with_items:
    - libvirt-daemon-kvm.x86_64
    - sysfsutils
  when: compute_virt_type == 'kvm'
  tags:
    - yum
    - lxc

- name: LXC packages
  yum: name="{{ item }}" state=present
  with_items:
    - lxc
    - lxc-libs
    - lxc-templates
    - libvirt-daemon-lxc.x86_64
    - libvirt-daemon-config-network.x86_64
    - python2-lxc
    - sysfsutils
  when: compute_virt_type == 'lxc'
  tags:
    - yum
    - lxc

- name: Remove setfcap from centos.common.conf
  copy:
    src: "files/lxc_centos.common.conf"
    dest: "/usr/share/lxc/config/centos.common.conf"
  when: compute_virt_type == 'lxc'
  tags:
    - lxc

- name: Restart libvirtd
  service: name=libvirtd state=restarted
