---
- name: Check KVM Hardware support
  shell: "egrep -c '(vmx|svm)' /proc/cpuinfo"
  register: support_kvm
  ignore_errors: true

- include: install_requirements.yml
- include: install_compute.yml
- include: configure_services.yml

- name: Start Compute service
  service: name="{{ item }}" state=started enabled=yes 
  with_items:
    - openstack-nova-compute
