---
- name: Create DB
  mysql_db:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_host: "localhost"
    name: "nova"
    state: "present"
  delegate_to: "{{ groups.mariadb.0 }}"
  tags:
    - create-db

- name: Create DB user
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_host: "localhost"
    name: "nova"
    password: "{{ nova_db_password }}"
    host: "{{ item }}"
    state: "present"
    priv: "nova.*:ALL"
  with_items:
    - "localhost"
    - "%"
  delegate_to: "{{ groups.mariadb.0 }}"

- name: Sync Glance DB
  command: "nova-manage db sync"
  become_user: nova
