---

- name: Remove firewalld
  yum: name=firewalld state=absent

- name: Custom ssh config
  become_user: "{{ lxc_container_user_name }}"
  copy: src="files/dot_ssh/config" dest="~/.ssh/config" mode=600 owner="{{ lxc_container_user_name }}"

- name: EPEL repository
  yum: name="{{ item }}" state=present
  with_items:
    - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
  tags:
    - yum

- name: Libselinux-python package installation
  yum: name=libselinux-python state=present

- name: Set selinux state to permissive
  selinux: policy=targeted state=permissive

- name: LXC packages
  yum: name="{{ item }}" state=present
  with_items:
    - lxc
    - lxc-libs
    - lxc-templates
    - libvirt-daemon-lxc.x86_64
    - libvirt-daemon-config-network.x86_64
    - python2-lxc
  tags:
    - yum

- name: Remove setfcap from centos.common.conf
  copy:
    src: "files/lxc_centos.common.conf"
    dest: "/usr/share/lxc/config/centos.common.conf"

- name: Copy LXC default config
  copy:
    src: "files/lxc_default.conf"
    dest: "/etc/lxc/default.conf"

- name: Restart libvirtd
  service: name=libvirtd state=restarted

- name: Enable LXC service
  service: name=lxc enabled=yes
