---

- name: Waiting for ping
  lxc_container:
    name: "{{ item }}"
    container_command: |
      ping -c 1 8.8.8.8
  register: lvm_container_info
  until: lvm_container_info.lxc_container.ips.0 is defined
  retries: 10
  delay: 30
  with_items: "{{ lxc_base_container }}"
  tags:
    - ping

- name: Install packages
  lxc_container:
    name: "{{ item }}"
    container_command: |
      yum -y update &&
      yum install -y sudo openssh-clients rsync &&
      sed --in-place 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+NOPASSWD:\s\+ALL\)/\1/' /etc/sudoers
      cat <<EOT >> /etc/sysconfig/network-scripts/ifcfg-eth1
      DEVICE=eth1
      BOOTPROTO=dhcp
      ONBOOT=yes
      HOSTNAME=
      NM_CONTROLLED=no
      TYPE=Ethernet
      DHCP_HOSTNAME=\`hostname\`
      EOT
  with_items: "{{ lxc_base_container }}"
  tags:
    - yum

- name: Create user
  lxc_container:
    name: "{{ item }}"
    container_command: |
      useradd --create-home -G wheel -s /bin/bash {{ lxc_container_user_name }}
  with_items: "{{ lxc_base_container }}"
  tags:
    - user

- name: Check key
  stat: path="/home/{{ lxc_container_user_name }}/.ssh/id_rsa.pub"
  register: pub_key
  tags:
    - ssh_key

- name: Generate ssh key
  shell: "ssh-keygen -q -f /home/{{ lxc_container_user_name }}/.ssh/id_rsa -N ''"
  when: not pub_key.stat.exists
  become_user: "{{ lxc_container_user_name }}"
  tags:
    - ssh_key

- name: Double check key
  stat: path="/home/{{ lxc_container_user_name }}/.ssh/id_rsa.pub"
  register: pub_key

- name: Add public rsa key to authorized_keys
  authorized_key: user={{ lxc_container_user_name }} key="{{ lookup('file', '/home/{{ lxc_container_user_name }}/.ssh/id_rsa.pub') }}"

- name: Force container user authorized_keys
  lxc_container:
    name: "{{ item }}"
    container_command: |
      getent passwd "{{ lxc_container_user_name }}" &&
      mkdir "/home/{{ lxc_container_user_name }}/.ssh" &&
      chmod 700 "/home/{{ lxc_container_user_name }}/.ssh" &&
      echo "{{ lookup('file', '/home/'+lxc_container_user_name+'/.ssh/id_rsa.pub') }}" > "/home/{{ lxc_container_user_name }}/.ssh/authorized_keys" &&
      chmod 600 "/home/{{ lxc_container_user_name }}/.ssh/authorized_keys" &&
      chown -R "{{ lxc_container_user_name }}":"{{ lxc_container_user_name }}" "/home/{{ lxc_container_user_name }}/.ssh"
  no_log: True
  when: pub_key.stat.exists
  with_items: "{{ lxc_base_container }}"
  tags:
    - ssh_key

- name: Tune resolv conf
  lxc_container:
    name: "{{ item }}"
    container_command: |
      cat <<EOT >> /etc/resolv.conf
      nameserver 192.168.53.254
      nameserver 192.168.122.1
      EOT
  with_items: "{{ lxc_base_container }}"
  when: num_controllers | int > 1

- name: Stop Base conainer
  lxc_container:
    name: "{{ lxc_base_container }}"
    state: stopped
