---
neutron_db_password: 'Zohchi0ik2Oowo5'
neutron_service_user_name: "neutron"
neutron_service_password: "Que5vohgahwebohh"
neutron_service_tenant_name: "service"
neutron_service_description: "OpenStack Networking"
neutron_service_region: "RegionOne"
neutron_service_name: "neutron"
neutron_service_type: "network"
neutron_service_publicurl: "http://{{ hostvars[groups.neutronService.0]['ansible_ssh_host'] }}:9696"
neutron_service_internalurl: "http://{{ hostvars[groups.neutronService.0]['ansible_ssh_host'] }}:9696"
neutron_service_adminurl: "http://{{ hostvars[groups.neutronService.0]['ansible_ssh_host'] }}:9696"
neutron_database_connection: "mysql://neutron:{{ neutron_db_password }}@{{ hostvars[groups.mariadb.0]['ansible_eth0']['ipv4']['address'] }}/neutron"
neutron_metadata_proxy_shared_secret: 'iPhoe2aviLi4uze2uR3v'
keystone_service_publicurl: "http://{{ hostvars[groups.keystone.0]['ansible_ssh_host'] }}:5000/v3"
keystone_service_internalurl: "http://{{ hostvars[groups.keystone.0]['ansible_ssh_host'] }}:5000/v3"
keystone_service_adminurl: "http://{{ hostvars[groups.keystone.0]['ansible_ssh_host'] }}:35357/v3"
keystone_service_adminurl_for_conf: "http://{{ hostvars[groups.keystone.0]['ansible_ssh_host'] }}:35357"
keystone_auth_admin_token: "Gee4soopohsusaki"
keystone_service_adminuri_insecure: true
keystone_rabbitmq_userid: "keystone"
keystone_rabbitmq_password: "Iengaiv1sahxughu"
keystone_rabbitmq_vhost_name: "keystone"
