---
remote_rsyslog: true
yum_repo_files:
  - name: "stackforce"
    descr: "Stackforce repository"
    baseurl: "http://repo.cloudlinux.com/stackforce/x86_64/"
    gpgcheck: 1
    enabled: 0
  - name: "stackforce-staging"
    descr: "Stackforce staging repository"
    baseurl: "http://repo.cloudlinux.com/stackforce-staging/x86_64/"
    gpgcheck: 1
    enabled: 1
  - name: "stackforce-testing"
    descr: "Stackforce testing repository"
    baseurl: "http://repo.cloudlinux.com/stackforce-testing/x86_64/"
    gpgcheck: 1
    enabled: 0
rpm_gpg_key_url: "http://repo.cloudlinux.com/stackforce-testing/RPM-GPG-KEY-CloudLinux"
