- name: Restart mysql
  service:
    name: mysql
    state: restarted
    args: "{{ (not percona_existing_cluster | bool and inventory_hostname == percona_server_bootstrap_node) | ternary('--wsrep-new-cluster', '') }}"
  environment:
    MYSQLD_STARTUP_TIMEOUT: 180
  when: not percona_running_and_bootstrapped | bool
  register: percona_restart
  # notifies are only fired when status is "changed"
  changed_when: percona_restart | failed
  failed_when: false
  notify:
    - "remove stale .sst"
    - "Restart mysql fall back"

- name: remove stale .sst
  file:
    path: "/var/lib/mysql/.sst"
    state: absent
  when: percona_restart | failed

- name: Restart mysql fall back
  service:
    name: mysql
    state: restarted
    args: "{{ (not percona_existing_cluster | bool and inventory_hostname == percona_server_bootstrap_node) | ternary('--wsrep-new-cluster', '') }}"
  environment:
    MYSQLD_STARTUP_TIMEOUT: 180
  when: percona_restart | failed
  register: percona_restart_fall_back
  until: percona_restart_fall_back | success
  retries: 3
  delay: 5

