---
- name: Ensure glance user
  keystone:
    command: "ensure_user"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    user_name: "{{ glance_service_user_name }}"
    tenant_name: "{{ glance_service_tenant_name }}"
    password: "{{ glance_service_password }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  tags:
    - glance-setup
- name: Ensure glance user to admin role
  keystone:
    command: "ensure_user_role"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    user_name: "{{ glance_service_user_name }}"
    tenant_name: "{{ glance_service_tenant_name }}"
    role_name: "admin"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  tags:
    - glance-setup
- name: Ensure glance service
  keystone:
    command: "ensure_service"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    service_name: "{{ glance_service_name }}"
    service_type: "{{ glance_service_type }}"
    description: "{{ glance_service_description }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  tags:
    - glance-setup
- name: Ensure glance endpoint
  keystone:
    command: "ensure_endpoint"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    region_name: "{{ glance_service_region }}"
    service_name: "{{ glance_service_name }}"
    service_type: "{{ glance_service_type }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
    endpoint_list:
      - url: "{{ glance_service_publicurl }}"
        interface: "public"
      - url: "{{ glance_service_internalurl }}"
        interface: "internal"
      - url: "{{ glance_service_adminurl }}"
        interface: "admin"
  tags:
    - glance-setup
