---
- include: install_packages.yml
- include: configure_services.yml
- include: services.yml
  when: inventory_hostname ==  "{{ groups['cinder'][0] }}"
- include: db_sync.yml
  when: inventory_hostname ==  "{{ groups['cinder'][0] }}"

- name: Start Cinder services
  service: name="{{ item }}" state=started enabled=yes
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
