---
- lvg: vg=cinder-volumes pvs="{{ cinder_disk }}"
  when: ("{{ cinder_disk }}" != "ceph")
- include: install_packages.yml
- include: configure_services.yml

- name: Start Cinder services
  service: name="{{ item }}" state=started enabled=yes
  with_items:
    - openstack-cinder-volume
    - target
- name: create openstack ceph key
  shell: "sudo ceph auth get-or-create client.openstack | sudo tee /etc/ceph/ceph.client.openstack.keyring"
  when: cinder_disk == "ceph"
