---
- lvg: vg=cinder-volumes pvs="{{ cinder_disk }}"
- include: install_packages.yml
- include: configure_services.yml

- name: Start Cinder services
  service: name="{{ item }}" state=started enabled=yes
  with_items:
    - openstack-cinder-volume
    - target
