---
- debug: var="{{ hostvars[groups.mariadb.0]['ansible_eth0']['ipv4']['address'] }}"
  tags:
    - create-db

- name: Install Keystone
  yum: name="{{ item }}" state=present
  with_items:
    - openstack-keystone
    - python-pip

- name: Install required pip packages
  pip: name=shade state=present

- name: Create config file
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf

- include: db_sync.yml

- include: rabbitmq.yml

- name: Ensure owner for log files
  file: path=/var/log/keystone recurse=yes owner=keystone group=keystone

- name: Start Keystone
  service: name=openstack-keystone state=started

- include: admin_openrc.yml

- include: service.yml

- name: Install opanstack-client
  yum: name=python-openstackclient state=present
