---
- name: Install Keystone
  yum: name="{{ item }}" state=present
  with_items:
    - openstack-keystone

- name: Create config file
  template:
    src: keystone.conf.j2
    dest: /etc/keystone/keystone.conf
  tags:
    - keystone-config

- include: db_sync.yml

- include: rabbitmq.yml

- name: Ensure owner for log files
  file: path="{{ item }}" recurse=yes owner=keystone group=keystone state=directory
  with_items:
    - /etc/keystone
    - /var/log/keystone

- name: Start Keystone
  service: name=openstack-keystone state=started

- include: admin_openrc.yml

- include: service.yml

- name: Install opanstack-client
  yum: name=python-openstackclient state=present
