---
- include: install_packages.yml
- include: configure_services.yml

- name: Start Neutron services
  service: name="{{ item }}" state=started
  with_items:
    - neutron-linuxbridge-agent
  delegate_to: localhost
