---
- name: Create DB
  mysql_db:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_host: "localhost"
    name: "neutron"
    state: "present"
  delegate_to: "{{ groups.mariadb.0 }}"
  tags:
    - create-db

- name: Create DB user
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_host: "localhost"
    name: "neutron"
    password: "{{ neutron_db_password }}"
    host: "{{ item }}"
    state: "present"
    priv: "neutron.*:ALL"
  with_items:
    - "localhost"
    - "%"
  delegate_to: "{{ groups.mariadb.0 }}"

- name: Sync Neutron DB
  command: "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head"
  become_user: neutron
