---
- name: Install Neutron packages
  vars:
      yum_retries: 3
  yum: name="{{ item }}" state=present
  with_items:
    - openstack-neutron
    - openstack-neutron-ml2
    - openstack-neutron-linuxbridge
    - python-neutronclient
    - ebtables
    - ipset
  register: yum_result
  until: yum_result.msg == "All items completed"
  retries: "{{ yum_retries }}"
