---
- include: install_packages.yml
- include: services.yml
  when: inventory_hostname ==  "{{ groups['controller'][0] }}"
- include: rabbitmq.yml
  when: inventory_hostname ==  "{{ groups['controller'][0] }}"
- include: configure_services.yml
- include: db_sync.yml
  when: inventory_hostname ==  "{{ groups['controller'][0] }}"

- name: Start Neutron services
  service: name="{{ item }}" state=started enabled=yes
  with_items:
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent

- include: consul.yml
