---
- include: install_packages.yml
- include: services.yml
- include: rabbitmq.yml
- include: configure_services.yml
- include: db_sync.yml

- name: Start Neutron services
  service: name="{{ item }}" state=started
  with_items:
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
