---
- hosts: baremetal*
  vars:
    - ntp_server: "ntp.lucky.net"
  roles:
       - { role: collectd,
             collectd_packages_RedHat:
             [{ package: "collectd" },
              { package: "collectd-lvm" }],
             collectd_plugins:
             [{ plugin: "load" },
              { plugin: "cpu" },
              { \#plugin: "contextswitch" },
              { plugin: "df" },
              { \#plugin: "disk" },
              { \#plugin: "ethstat" },
              { \#plugin: "interface" },
              { \#plugin: "network" },
              { \#plugin: "processes" },
              { \#plugin: "swap" },
              { \#plugin: "tcpconns" },
              { \#plugin: "uptime" },
              { plugin: "memory" }],
             collectd_plugins_multi:
             { write_graphite: "  <Node \"{{ ansible_hostname }}\">\n
                                   Host \"{{ hostvars[groups.graphite.0]['ansible_host'] }}\"\n
                                   Port \"2003\"\n
                                   Protocol \"tcp\"\n
                                   LogSendErrors true\n
                                   Prefix \"collectd\"\n
                                   Postfix \"collectd\"\n
                                   StoreRates true\n
                                   AlwaysAppendDS false\n
                                   EscapeCharacter \"_\"\n
                                  </Node>\n"},
              tags: ["collectd"] }

  tasks:
  - name: Ensure Collectd service is enabled and restarted
    service: name=collectd enabled=yes state=restarted

  - name: Install ntpd
    yum: name="{{ item }}" state=present
    with_items:
      - ntp

  - name: Check ntp socket
    shell: ss -aln sport = :123 |grep 123 | wc -l
    register: ntpd_status

  - name: Force sync time
    command: "ntpdate {{ ntp_server }}"
    when: ntpd_status.stdout == "0"

  - name: Start ntpd
    service: name=ntpd state=started enabled=yes
