---
- hosts: controller*
  become: yes
  become_method: sudo
  vars:
    public_address: "{{ lookup('ini', 'address section=public file=/etc/stackforce/parameters.ini') }}"
    inventory: "../test/inventory/vagrant"
    containers: "files/allinone_containers.yml"
    parameters: "../test/playbooks/templates/parameters.ini.j2"
    inventory_filepath: "/etc/stackforce/inventory"
    unique_containers_file: "/etc/stackforce/containers.yml"
  tasks:
  - name: Install consul-ui
    yum: name="{{ item }}" state=present
    with_items:
      - http://stackforce.cloudlinux.com/repos/consul-0.6.3-1.el7.centos.x86_64.rpm
      - http://stackforce.cloudlinux.com/repos/consul-ui-0.6.3-1.el7.centos.x86_64.rpm

  - name: Default consul config
    template: src=consul.json.j2 dest=/etc/consul/consul.json owner=root group=consul
    register: consul_cfg

  - name: Enable consul
    service: name=consul state=restarted enabled=yes
    when: consul_cfg|changed

  - name: join consule to cluster
    shell: "consul join {{ hostvars[groups.controller.0]['ansible_mngt_br']['ipv4']['address'] }}"
    when: inventory_hostname !=  "{{ groups['controller'][0] }}"

  - name: Install necessary packages
    yum:
      name: "{{ item }}"
      state: installed
      enablerepo: "stackforce-testing"
    with_items:
      - python2-lxc
      - ansible
