# vim:ft=ansible:
---
- hosts: controller*
  become: yes
  become_method: sudo
  vars:
    remote_rsyslog: false
    lxc_base_container: "stackforce_base_container"
    num_controllers:  "{{ groups['controller'] | length }}"
  roles:
    - role: common
    - role: create_lxc
