# vim:ft=ansible:
---
- hosts: all
  gather_facts: none
  sudo: yes
  vars:
    lxc_base_container: "stackforce_base_container"
    lxc_containers:
      - "rabbitmq_container-0cac5cd9"
      - "mariadb_container-f4e260fa"
      - "syslog_container-c2a56e86"
      - "keystone_container-2dc354cb"
      - "horizon_container-81aca944"
    lxc_container_user_name: "sdeviatkin"
    lxc_container_template_options: >
      --user {{ lxc_container_user_name }}
  tasks:
  - lvg: vg=lxc pvs=/dev/sdb
    tags:
      - lvm

  - name: Custom ssh config
    copy: src="files/dot_ssh/config" dest="~/.ssh/config" mode=600 owner="{{ lxc_container_user_name }}"
    sudo_user: "{{ lxc_container_user_name }}"

  - name: EPEL repository
    yum: name="{{ item }}" state=present
    with_items:
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    tags:
      - yum

  - name: LXC packages
    yum: name="{{ item }}" state=present
    with_items:
      - lxc
      - lxc-libs
      - lxc-templates
      - libvirt-daemon-lxc.x86_64
      - libvirt-daemon-config-network.x86_64
      - "http://stackforce.cloudlinux.com/repos/lxc-python2-0.1-1.x86_64.rpm"
    tags:
      - yum

  - name: Remove setfcap from centos.common.conf
    shell: "sed -i 's/setfcap$//' /usr/share/lxc/config/centos.common.conf"

  - name: Restart libvirtd
    service: name=libvirtd state=restarted

  - name: Create a base container
    lxc_container:
      name: "{{ lxc_base_container }}"
      container_log: true
      template: centos
      state: stopped
      backing_store: lvm
      vg_name: "lxc"
      container_config:
        - lxc.kmsg=0
    tags:
      - lxc
      - lxc-base-container

  - name: Clone containers
    shell: "echo lxc-clone -o {{ lxc_base_container }} -n {{ item }}"
    with_items: lxc_containers
    tags:
      - lxc
      - lxc-clone-containers

  - name: Create a started container
    lxc_container:
      name: "{{ item }}"
      container_log: true
      template: centos
      state: started
      backing_store: lvm
      vg_name: "lxc"
      container_config:
        - lxc.kmsg=0
    with_items: lxc_containers
    tags:
      - lxc
      - lxc-start-containers

  - name: Create user
    lxc_container:
      name: "{{ item }}"
      container_command: |
        useradd --create-home -G wheel -s /bin/bash {{ lxc_container_user_name }}
    with_items: lxc_containers
    tags:
      - user

  - name: Check key
    stat: path="/home/{{ lxc_container_user_name }}/.ssh/id_rsa.pub"
    register: pub_key
    tags:
      - ssh_key

  - name: Generate ssh key
    shell: "ssh-keygen -q -f /home/{{ lxc_container_user_name }}/.ssh/id_rsa -N ''"
    when: not pub_key.stat.exists
    sudo_user: "{{ lxc_container_user_name }}"
    tags:
      - ssh_key

  - name: Double check key
    stat: path="/home/{{ lxc_container_user_name }}/.ssh/id_rsa.pub"
    register: pub_key

  - name: Force container user authorized_keys
    lxc_container:
      name: "{{ item }}"
      container_command: |
        getent passwd "{{ lxc_container_user_name }}" &&
        mkdir "/home/{{ lxc_container_user_name }}/.ssh" &&
        chmod 700 "/home/{{ lxc_container_user_name }}/.ssh" &&
        echo "{{ lookup('file', '/home/'+lxc_container_user_name+'/.ssh/id_rsa.pub') }}" > "/home/{{ lxc_container_user_name }}/.ssh/authorized_keys" &&
        chmod 600 "/home/{{ lxc_container_user_name }}/.ssh/authorized_keys" &&
        chown -R "{{ lxc_container_user_name }}":"{{ lxc_container_user_name }}" "/home/{{ lxc_container_user_name }}/.ssh"
    no_log: True
    when: pub_key.stat.exists
    with_items: lxc_containers
    tags:
      - ssh_key

  - name: Waiting for ping
    lxc_container:
      name: "{{ item }}"
      container_command: |
        ping -c 1 8.8.8.8
    register: lvm_container_info
    until: lvm_container_info.lxc_container.ips.0 is defined
    retries: 10
    delay: 30
    with_items: lxc_containers
    tags:
      - ping

  - name: Install packages
    lxc_container:
      name: "{{ item }}"
      container_command: |
        yum update &&
        yum install -y sudo openssh-clients rsync &&
        sed --in-place 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+NOPASSWD:\s\+ALL\)/\1/' /etc/sudoers
    with_items: lxc_containers
    tags:
      - yum
