---
- hosts: all

- include: rabbitmq.yml
- include: mariadb.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
- include: os-keystone.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
- include: rsyslog.yml
- include: os-horizon.yml
- include: os-glance.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
