---
- hosts: all
  roles:
    - role: consul-agent
  serial: 3

- include: controller.yml
- include: rabbitmq.yml
- include: mariadb.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
- include: memcached.yml
  vars:
    memcached_listen_ip: "0.0.0.0"
- include: os-keystone.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
    public_address: "{{ lookup('ini', 'address section=public file=/etc/stackforce/parameters.ini') }}"
    keystone_service_publicurl: "http://{{ public_address }}:5000/v3"
    keystone_service_adminurl: "http://{{ public_address }}:35357/v3"

- include: rsyslog.yml
- include: os-horizon.yml
- include: os-glance.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
    public_address: "{{ lookup('ini', 'address section=public file=/etc/stackforce/parameters.ini') }}"
    glance_service_publicurl: "http://{{ public_address }}:9292"
    glance_service_adminurl: "http://{{ public_address }}:9292"

- include: os-nova-api.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
    public_address: "{{ lookup('ini', 'address section=public file=/etc/stackforce/parameters.ini') }}"
    nova_service_publicurl: "http://{{ public_address }}:8774/v2/%(tenant_id)s"
    nova_service_adminurl: "http://{{ public_address }}:8774/v2/%(tenant_id)s"
    nova_neutron_url: "http://{{ public_address }}:9696"
- include: os-cinder-api.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
    public_address: "{{ lookup('ini', 'address section=public file=/etc/stackforce/parameters.ini') }}"
    cinder_service_publicurl: "http://{{ public_address }}:8776/v1/%(tenant_id)s"
    cinder_service_adminurl: "http://{{ public_address }}:8776/v1/%(tenant_id)s"
    cinder_service_v2_publicurl: "http://{{ public_address }}:8776/v2/%(tenant_id)s"
    cinder_service_v2_adminurl: "http://{{ public_address }}:8776/v2/%(tenant_id)s"
  tags:
    - install_cinder
- include: os-compute.yml
  vars:
    compute_virt_type: 'lxc'
    public_address: "{{ lookup('ini', 'address section=public file=/etc/stackforce/parameters.ini') }}"
    neutron_service_publicurl: "http://{{ public_address }}:9696"

- include: os-neutronService.yml
  vars:
    os_verbose: "True"
    os_debug: "True"
    mysql_root_password: 'Jovoh4aceloduush'
    public_address: "{{ lookup('ini', 'address section=public file=/etc/stackforce/parameters.ini') }}"
    neutron_service_publicurl: "http://{{ public_address }}:9696"
    neutron_service_adminurl: "http://{{ public_address }}:9696"
    neutron_service_internalurl: "http://{{ public_address }}:9696"
    neutron_nova_metadata_ip: "{{ public_address }}"
- include: os-neutronAgent.yml
- include: os-cinder-storage.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
    public_address: "{{ lookup('ini', 'address section=public file=/etc/stackforce/parameters.ini') }}"
  tags:
    - install_cinder
