---
- hosts: all

- include: rabbitmq.yml
- include: mariadb.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
- include: memcached.yml
  vars:
    memcached_listen_ip: "0.0.0.0"
- include: os-keystone.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
    public_address: "{{ lookup('ini', 'address section=public file=/etc/stackforce/parameters.ini') }}"
    keystone_service_publicurl: "http://{{ public_address }}:5000/v3"
    keystone_service_adminurl: "http://{{ public_address }}:35357/v3"

- include: rsyslog.yml
- include: os-horizon.yml
- include: os-glance.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
    public_address: "{{ lookup('ini', 'address section=public file=/etc/stackforce/parameters.ini') }}"
    glance_service_publicurl: "http://{{ public_address }}:9292"
    glance_service_adminurl: "http://{{ public_address }}:9292"

- include: os-neutronService.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
- include: os-neutronAgent.yml
- include: os-nova-api.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
- include: os-compute.yml
  vars:
    compute_virt_type: 'lxc'
- include: os-cinder-api.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
  tags:
    - install_cinder
