---
- hosts: all

- include: rabbitmq.yml
- include: mariadb.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
- include: os-keystone.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
    public_address: "{{ lookup('ini', 'address section=public file=/etc/stackforce/parameters.ini') }}"
    keystone_service_publicurl: "http://{{ public_address }}:5000/v3"
- include: rsyslog.yml
- include: os-horizon.yml
- include: os-glance.yml
  vars:
    mysql_root_password: 'Jovoh4aceloduush'
