---
glance_db_user: "glance"
glance_db_password: "Que5vohgahwebohh"
glance_service_password: "Que5vohgahwebohh"
glance_service_user_name: "glance"
glance_service_tenant_name: "service"
glance_service_project_name: "admin"
glance_service_name: "glance"
glance_service_type: "image"
glance_service_region: "RegionOne"
glance_service_description: "OpenStack Image service"
glance_service_publicurl: "http://{{ public_address }}:9292"
glance_service_internalurl: "http://{{ public_address }}:9292"
glance_service_adminurl: "http://{{ public_address }}:9292"
glance_database_connection: "mysql://glance:{{ glance_db_password }}@{{ public_address }}/glance"
glance_default_store: "file"
glance_filesystem_store_datadir: "/var/lib/glance/images/"
keystone_service_publicurl: "http://{{ public_address }}:5000/v3"
keystone_service_internalurl: "http://{{ public_address }}:5000/v3"
keystone_service_adminurl: "http://{{ public_address }}:35357/v3"
keystone_auth_admin_token: "Gee4soopohsusaki"
keystone_service_adminuri_insecure: true
glance_rbd_pool: "images"
glance_ceph_user: "openstack"
